# Generated by Django 5.0.2 on 2024-02-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('score_1', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('score_2', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('winner', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to='players.player')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament', to='tournaments.tournament')),
            ],
        ),
    ]
