# Generated by Django 5.0.2 on 2024-02-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_round_alter_game_tournament'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'tournament')},
        ),
    ]
