# Generated by Django 5.0.2 on 2024-02-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_game_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='round',
            new_name='game_round',
        ),
    ]
