# Generated by Django 5.0.2 on 2024-02-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='tournaments.tournament')),
            ],
        ),
    ]
