# Generated by Django 4.0 on 2024-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_description'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ManyToManyField(related_name='players', to='tournaments.Tournament'),
        ),
    ]
