# Generated by Django 5.0.2 on 2024-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_tournament'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='tournaments.tournament'),
        ),
    ]
